name: "terraform-build"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Choose Environment
      aws-region:
        type: string
        required: true
        description: Choose AWS Region
      apply-terraform:
        type: boolean
        required: true
        description: Terraform Apply
    secrets:
      aws-env-access-key:
        required: true
      aws-env-secret-key:
        required: true
      aws-general-access-key:
        required: true
      aws-general-secret-key:
        required: true

env:
  subfolder: terraform
  project-name: vabland

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "setup: repository"
        uses: actions/checkout@v3.1.0

      - name: "setup: aws-cli"
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ inputs.aws-region }}
          aws-access-key-id: ${{ secrets.aws-env-access-key }}
          aws-secret-access-key: ${{ secrets.aws-env-secret-key }}

      - name: "setup: terraform"
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.3.3
      
      - name: "terraform: init"
        shell: bash
        run: terraform -chdir=${{ env.subfolder }} init -var-file="main.tfvars"
      
      - name: "terraform: plan"
        shell: bash
        run: terraform -chdir=${{ env.subfolder }} plan -var-file="main.tfvars" -input=false
        env:
          TF_VAR_environment: ${{ inputs.environment }}
          TF_VAR_aws_env_access_key: ${{ secrets.aws-env-access-key }}
          TF_VAR_aws_env_secret_key: ${{ secrets.aws-env-secret-key }}
          TF_VAR_aws_general_access_key: ${{ secrets.aws-general-access-key }}
          TF_VAR_aws_general_secret_key: ${{ secrets.aws-general-secret-key }}

      - name: "terraform: apply"
        if: inputs.apply-terraform == 'True'
        shell: bash
        run: terraform -chdir=${{ env.SUBFOLDER }} apply -var-file="main.tfvars" -input=false -auto-approve
        env:
          TF_VAR_environment: ${{ inputs.environment }}
          TF_VAR_aws_env_access_key: ${{ secrets.aws-env-access-key }}
          TF_VAR_aws_env_secret_key: ${{ secrets.aws-env-secret-key }}
          TF_VAR_aws_general_access_key: ${{ secrets.aws-general-access-key }}
          TF_VAR_aws_general_secret_key: ${{ secrets.aws-general-secret-key }}